<?php
return [
    'allowed_mime_types' => [
        'image/jpeg','image/jpg','image/png','image/gif','image/webp',
        'image/tiff','image/bmp','image/heic','image/heif','image/svg+xml',
        'image/x-adobe-dng','image/x-canon-cr2','image/x-canon-cr3',
        'image/x-nikon-nef','image/x-sony-arw','image/x-fuji-raf',
        'video/mp4','video/quicktime','video/x-msvideo','video/x-matroska',
        'video/webm','video/mpeg','video/3gpp','video/3gpp2',
        'video/x-flv','video/x-ms-wmv','video/x-m4v','video/MP2T',
        'application/mxf','video/mxf',
    ],
    'max_upload_size_mb'  => env('MAX_UPLOAD_SIZE_MB', 500),
    'max_batch_size'      => env('MAX_BATCH_SIZE', 500),
    'max_batch_size_mb'   => env('MAX_BATCH_SIZE_MB', 2048),
    'processing' => [
        'default_run_forensics'  => env('DEFAULT_RUN_FORENSICS', true),
        'default_run_ai'         => env('DEFAULT_RUN_AI', true),
        'default_run_geospatial' => env('DEFAULT_RUN_GEOSPATIAL', true),
        'ela_quality'            => env('ELA_QUALITY', 75),
        'ela_scale'              => env('ELA_SCALE', 10),
        'video_max_frames'       => env('VIDEO_MAX_FRAMES', 48),
        'video_frame_interval_s' => env('VIDEO_FRAME_INTERVAL_S', 15),
        'thumbnail_width'        => 320,
        'thumbnail_height'       => 240,
    ],
    'exiftool_path'   => env('EXIFTOOL_PATH',  '/usr/bin/exiftool'),
    'ffprobe_path'    => env('FFPROBE_PATH',   '/usr/bin/ffprobe'),
    'ffmpeg_path'     => env('FFMPEG_PATH',    '/usr/bin/ffmpeg'),
    'mediainfo_path'  => env('MEDIAINFO_PATH', '/usr/bin/mediainfo'),
    'report_ttl_days' => env('REPORT_TTL_DAYS', 7),
    'elasticsearch'   => ['images_index' => env('ES_IMAGES_INDEX','metaintel_media')],
    'security' => [
        'api_key_prefix'     => 'mi_',
        'api_key_length'     => 48,
        'webhook_secret_len' => 48,
        'max_api_keys'       => 10,
    ],
];
